/*
 * grunt-haibu-deploy
 *
 */

module.exports = function(grunt) {
    'use strict';

    // Project configuration.
    grunt.initConfig({
        jshint: {
            all: [
                'Gruntfile.js',
                'tasks/*.js',
                '<%= nodeunit.tests %>'
            ],
            options: {
                jshintrc: '.jshintrc'
            }
        },

        // Before generating any new files, remove any previously-created files.
        clean: {
            test: ['tmp']
        },

        // Configuration to be run (and then tested).
        haibu: {
            options: {

                // Server setting
                haibuHost: 'http://localhost',
                haibuPort: 9002,
                userName: 'node',

                // Override package.json's app property
                appName: '',

                /*
                 * This directory will be used to find package.json for normal mode, and
                 * include file for static mode.
                 */
                path: './test/fixtures/hellonode',

                // Start script which is auto-generated by haibu deployment system.
                startScript: 'start.js',

                includeFile: '.haibuinclude'
            },
            haibutest1: {
                options: {
                    mode: 'normal',
                    port: 11000,

                    // Starting point.
                    initScript: 'server.js'
                }
            },
            haibutest2: {
                options: {
                    mode: 'static',
                    port: 11010,

                    // Directory to serve, relative to options.path
                    staticDir: '.'
                }
            }
        },

        // Unit tests.
        nodeunit: {
            tests: ['test/*_test.js']
        }
    });

    // Actually load this plugin's task(s).
    grunt.loadTasks('tasks');

    // These plugins provide necessary tasks.
    grunt.loadNpmTasks('grunt-contrib-jshint');
    grunt.loadNpmTasks('grunt-contrib-clean');
    grunt.loadNpmTasks('grunt-contrib-nodeunit');

    // Whenever the "test" task is run, first clean the "tmp" dir, then run this
    // plugin's task(s), then test the result.
    grunt.registerTask('test', ['clean', 'haibu-deploy', 'nodeunit']);

    // By default, lint and run all tests.
    grunt.registerTask('default', ['jshint', 'test']);

};