/*
 * grunt-haibu-deploy
 *
 */

module.exports = function(grunt) {
    'use strict';

    // Project configuration.
    grunt.initConfig({
        jshint: {
            all: [
                'Gruntfile.js',
                'tasks/*.js',
                '<%= nodeunit.tests %>'
            ],
            options: {
                jshintrc: '.jshintrc'
            }
        },

        // Before generating any new files, remove any previously-created files.
        clean: {
            test: ['tmp']
        },

        // Configuration to be run (and then tested).
        haibu: {
            options: {

                // Haibu server protocol. (Default: http)
                haibuProtocol: 'http',

                // Haibu server domain name. (Required)
                haibuDomain: 'localhost',

                // Haibu server subdomain name. (Optional)
                // haibuSubdomain: 'deploy',

                // Haibu server port. (Default: 80)
                haibuPort: 9002,

                // Haibu user.
                userName: 'node',

                // Override package.json's app property. (Optional)
                appName: '',

                /*
                 * This directory will be used to find package.json for normal mode,
                 * and cwd for static mode. (Default: '.')
                 */
                path: './test/fixtures/hellonode',

                // Start script which is auto-generated by haibu deployment system. (Default: 'start.js')
                startScript: 'start.js',

                // File specifies file to deploy. (Default: .haibuinclude)
                includeFile: '.haibuinclude',

                // Task which should run before deployment. (Optional)
                prevTasks: ['clean'],

                // Print result with target as subdomain when deploy is finished. (Default: false)
                subdomainEqualsToTarget: true,

                /*
                 * Ask if deployment should be continued
                 * when multiple deployment is started. (Default: true)
                 */
                askWhenMultiDeploy: true
            },
            test1: {
                options: {

                    /*
                     * Deploy mode.
                     *
                     * 'normal' mode is used for most node apps which has script to run.
                     * The init script must be specified in options.initScript.
                     *
                     * 'static' mode is used for static deployment.
                     * Directory to server must be specified in options.staticDir.
                     */
                    mode: 'normal',

                    // Port to deploy.
                    port: 11000,

                    // Starting point. this used in normal mode. (Required)
                    initScript: 'server.js',

                    // Custom subdomain. (Optional)
                    //subdomain: ''
                }
            },
            test2: {
                options: {
                    mode: 'static',
                    port: 11010,

                    // Directory to serve, relative to options.path (Required)
                    staticDir: '.'
                }
            },
            test3: {
                options: {
                    mode: 'static',
                    port: 11020,

                    // Directory to serve, relative to options.path (Required)
                    staticDir: '.'
                }
            }
        },

        // Unit tests.
        nodeunit: {
            tests: ['test/*_test.js']
        }
    });

    // Actually load this plugin's task(s).
    grunt.loadTasks('tasks');

    // These plugins provide necessary tasks.
    grunt.loadNpmTasks('grunt-contrib-jshint');
    grunt.loadNpmTasks('grunt-contrib-clean');
    grunt.loadNpmTasks('grunt-contrib-nodeunit');

    // Whenever the "test" task is run, first clean the "tmp" dir, then run this
    // plugin's task(s), then test the result.
    grunt.registerTask('test', ['clean', 'haibu', 'nodeunit']);

    // By default, lint and run all tests.
    grunt.registerTask('default', ['jshint', 'test']);

};
